<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://xmlns.ec.eu/BusinessActivityService/AEOI_DAC7/StatusMessageBAS/V1"
  targetNamespace="http://xmlns.ec.eu/BusinessActivityService/AEOI_DAC7/StatusMessageBAS/V1" name="StatusMessageBAS"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://www.w3.org/2005/08/addressing"
  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:ccn2="http://ccn2.ec.eu/">
  
  <wsdl:import namespace="http://xmlns.ec.eu/BusinessActivityService/AEOI_DAC7/StatusMessageBAS/V1"
    location="CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS_1.0.0_1.1.0.wsdl" />
    
  <wsdl:binding name="StatusMessageBASSoapBinding" type="StatusMessageBAS">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsp:PolicyReference URI="#username_supporting_token_plaintext_password" />
    <wsdl:operation name="send">
      <soap12:operation soapAction="CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS/send" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ccnFault">
        <soap12:fault name="ccnFault" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS">
    <wsdl:port name="StatusMessageBAS" binding="StatusMessageBASSoapBinding">
      <soap12:address location="http://{ccn2_address}/CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS" />
      <wsa:EndpointReference>
        <wsa:Address>http://{ccn2_address}/CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS</wsa:Address>
        <wsa:Metadata>
		  <ccn2:XMLValidation>false</ccn2:XMLValidation>
          <ccn2:ServiceID>CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS</ccn2:ServiceID>
          <ccn2:ServiceName>CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS</ccn2:ServiceName>
          <ccn2:ServiceDescription>CCN2.Service.Taxation.Default.AEOI_DAC7.StatusMessageBAS</ccn2:ServiceDescription>
          <ccn2:ServiceVersion>http://ccn2.ec.eu/Version/1.0.0</ccn2:ServiceVersion>
        </wsa:Metadata>
      </wsa:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>